[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
verbosity = 2
optimizer = true
optimizer-runs = 500
solc_version = '0.8.18'
evm_version = 'paris'
fs_permissions = [{ access = 'read', path = './'}]
ffi = true

[fuzz]
runs = 1_000
fail_on_revert = true

[rpc_endpoints]
baseGoerli = "${BASE_GOERLI_RPC_URL}"

[etherscan]
baseGoerli = { key = "${BASE_ETHERSCAN_API_KEY}" }

[doc]
title = "Flatcoin V1"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config